global:
  scrape_interval: 15s # By default, scrape targets every 5 seconds.
  scrape_timeout: 10s
  evaluation_interval: 1m

alerting:
  alertmanagers:
  - follow_redirects: true
    enable_http2: true
    scheme: http
    timeout: 10s
    api_version: v2
    static_configs:
    - targets: []

scrape_configs:

- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ["prometheus:9090"]

- job_name: grafana
  honor_timestamps: true
  scrape_interval: 10s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ["grafana:3000"]

- job_name: prometheus-exporter-solarapp
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
    - targets: ["prometheus-exporter-solarapp:7979"]     

- job_name: nodejs-solarapp
  honor_timestamps: true
  scrape_interval: 1m
  scrape_timeout: 15s
  metrics_path: /probe
  scheme: http
  static_configs:
    - targets:
      - http://nodejs-solarapp:9876
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      ## Location of the json exporter's real <hostname>:<port>
      replacement: prometheus-exporter-solarapp:7979 # equivalent to "localhost:7979"
