{
 "title": "Node JS Solar App",
 "tags": [
  "solarapp",
  "inverter",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "House Consumption",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_solarapp_houseConsumption",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Generation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_pv", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_batteryP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Power",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_gridP", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery SOC",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_batterySOC", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_batteryMode", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Temp.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_solarapp_batteryTemperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery SOH",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_batterySOH", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Grid Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nodejs_solarapp_gridInOutMode", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Inverter Temp.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nodejs_solarapp_inverterTemperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "nodejs_solarapp_gridP", "legendFormat": "Grid" },
    { "expr": "nodejs_solarapp_batteryP", "legendFormat": "Battery" },
    {
     "expr": "nodejs_solarapp_houseConsumption",
     "legendFormat": "House Consumption"
    },
    { "expr": "nodejs_solarapp_pv", "legendFormat": "PV" },
    { "expr": "nodejs_solarapp_batterySOC", "legendFormat": "Battery %" }
   ]
  },
  {
   "title": "Inverter Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nodejs_solarapp_inverterTemperature",
     "legendFormat": "Inverter"
    },
    {
     "expr": "nodejs_solarapp_batteryTemperature",
     "legendFormat": "Battery"
    }
   ]
  }
 ]
}