FROM grafana/grafana-oss:9.5.2

RUN grafana-cli plugins install yesoreyeram-infinity-datasource
RUN grafana-cli plugins install grafana-clock-panel
RUN grafana-cli plugins install marcusolsson-json-datasource
RUN grafana-cli plugins install grafana-simple-json-datasource
